name: Deploy Flask App

on:
  push:
    branches:
      - main  # Adjust to your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up SSH for the VM
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/challenge.pem
        chmod 600 ~/.ssh/challenge.pem
        echo "Host 20.127.206.174
              StrictHostKeyChecking no
              User azureuser
              IdentityFile ~/.ssh/challenge.pem" > ~/.ssh/config
        chmod 600 ~/.ssh/config

    # Step 3: Install dependencies and deploy the app
    - name: Deploy to VM
      run: |
        ssh azureuser@20.127.206.174 << 'EOF'
        # Ensure Python and pip are installed
        sudo apt update
        sudo apt install -y python3-pip python3-venv

        # Set up a virtual environment and Flask app
        python3 -m venv ~/flask-env
        source ~/flask-env/bin/activate
        pip install flask

        # Stop any running app (optional)
        sudo pkill -f hello.py || true

        # Deploy and run the app
        nohup sudo ~/flask-env/bin/python /home/azureuser/hello.py > ~/flask-app.log 2>&1 &
        EOF
      shell: bash
