name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VM
      run: |
        scp -i ~/.ssh/id_rsa ~/.ssh/challenge.pem azureuser@20.127.206.174:/home/azureuser/.ssh/
        ssh -i ~/.ssh/id_rsa azureuser@20.127.206.174 "sudo apt update && sudo apt install python3-pip -y"
        ssh -i ~/.ssh/id_rsa azureuser@20.127.206.174 "pip3 install --upgrade pip"
        ssh -i ~/.ssh/id_rsa azureuser@20.127.206.174 "pip3 install flask"
        ssh -i ~/.ssh/id_rsa azureuser@20.127.206.174 "nohup python3 /home/azureuser/hello.py &"
